### PR TITLE
Fixed example for RPLidar firmware 1.29

### PR DESCRIPTION
**Pull request by zlite**
Uses latest PR from @makermelissa 

Fixed example to include timeout=3, which is necessary on latest firmware. Some other fixes to example, such as corrected package name since it does not currently support circuitpython.

Tested on RPLidar firmware 1.29 and the previous firmware, 1.27, so should work on all RPLidars now

### CODE REVIEW

**Comment by ladyada** [comment]
yay awesome for the community working together!

**Comment by makermelissa** [comment]
Fixing CRLF wasn't working through web interface and I finally figured out how to correctly push remotely to another user's repo through command line.

**Comment by zlite** [comment]
Thanks @makermelissa! It's weird that the linter was rejecting the line endings. I just edited the file in Github's own web editor!

**Comment by makermelissa** [comment]
Yeah, same here initially.

**Pull request merged**
